---------------------------------------------
--- THIS FILE IS AUTOGENERATED BY WALLUST ---
---        SEE ~/.config/wallust/         ---
---------------------------------------------

return {
  base_16 = {
    base00 = "{{background}}",
  },
}
