[config]
caching = true

[templates.waybar]
input_path = "./templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.swaync]
input_path = "./templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.eww]
input_path = "./templates/eww-colors.scss"
output_path = "~/.config/eww/colors.scss"
