[config]
caching = true

[templates.waybar]
input_path = "./templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
