add_newline = true

format = """
$cmd_duration$directory$git_branch
$character"""

[character]
success_symbol = "[  ](bold fg:blue)"
error_symbol = "[  ](bold fg:red)"

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = "••"
format = " [](bold fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[ ](bold fg:cyan)"

[directory]
home_symbol = "  "
read_only = "  "
style = "bg:yellow fg:black"
truncation_length = 6
truncation_symbol = " ••/"
format = '[](bold fg:yellow)[󰉋 $path]($style)[](bold fg:yellow)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 3000
format = '[](bold fg:yellow)[󰔟 $duration](bold bg:yellow fg:black)[](bold fg:yellow) '
